fix(release): Add missing dependency fetch step (#72)
# Description
Add missing dependency fetch step to prevent `helm-releaser` error:

```
Error: no repository definition for https://opensearch-project.github.io/helm-charts/, https://opensearch-project.github.io/helm-charts/
```